Feature/button component
isdi-coders-2023/coding-adventure-Sergi-Casquero-front-202301-BCN pull request #1
Opened 2023-02-27 16:09 UTC by Sergi-CM

2023-02-27 16:16 UTC, catatarelli submitted a review, later dismissed

2023-02-27 16:16 UTC, catatarelli commented on src/components/Button/ButtonStyled.ts
> +  background-color: #cccf18;
los colores los podemos sacar a variables o un Theme Provider?

2023-02-27 16:16 UTC, catatarelli commented on src/globalStyles.tsx
> +  h1,h2{
espacio antes de la llave

2023-02-27 16:16 UTC, catatarelli commented on src/globalStyles.tsx
> +  button{
aca tambien espacio

2023-02-27 16:51 UTC, Sergi-CM commented on src/components/Button/Button.test.tsx
> +  describe("When rendered passing", () => {
Ay.. me quedé pensando y se me olvidó

2023-02-27 16:51 UTC, Sergi-CM commented on src/components/Button/ButtonStyled.ts
> +  background-color: #cccf18;
Hecho

2023-02-27 16:51 UTC, Sergi-CM commented on src/globalStyles.tsx
> +  h1,h2{
Hecho

2023-02-27 16:51 UTC, Sergi-CM commented on src/globalStyles.tsx
> +  button{
Hecho

2023-02-27 16:55 UTC, MMLORENA commented on src/components/Button/ButtonStyled.ts
> +  background-color: #cccf18;
No lo veo

2023-02-27 16:55 UTC, MMLORENA commented on src/globalStyles.tsx
> +  button{
No lo veo

2023-02-27 16:55 UTC, MMLORENA requested changes
La descripción del commit no es del todo claro

2023-02-27 17:09 UTC, MMLORENA requested changes

2023-02-27 17:09 UTC, MMLORENA commented on src/App.tsx
> +  return <Button text="Sign Up" />;
El enunciado no habla de instanciarlo en App

2023-02-27 17:09 UTC, MMLORENA commented on src/components/Button/ButtonStyled.ts
>    font-family: "saira stencil one", sans-serif;
Ya que usas las props del theme, debería estar también la fuente

2023-02-27 17:09 UTC, MMLORENA commented on src/styles/theme.ts
> +const theme = {
Te invito a que revises la docu de ThemeProvider para typarlo y así te ayudará a autocompletar la forma del theme. Pero enhorabuena por atraverte a usarlo

2023-02-27 17:09 UTC, MMLORENA commented on src/components/Button/ButtonStyled.ts
>    font-family: "saira stencil one", sans-serif;
Y tamaños que veas que se repiten

2023-02-27 17:10 UTC, MMLORENA commented
@Sergi-CM Te han fallado en dos commits el workflow de Testing. Revisa porqué

2023-02-28 11:13 UTC, Sergi-CM commented on src/styles/theme.ts
> +const theme = {
@MMLORENA Todo listo

2023-02-28 11:17 UTC, MMLORENA requested changes

2023-02-28 11:17 UTC, MMLORENA commented on src/styles/theme.ts
> +    mainFontSize: "1rem",
No lo cambies ahora, pero para la próxima creo que iría mejor separar tamaños en tamaños, fuentes en fuentes.

2023-02-28 11:17 UTC, MMLORENA commented on src/styles/types.ts
> +interface ThemeStructure {
Recomiendo que busques el tipado del theme de styled components

2023-02-28 11:34 UTC, Sergi-CM commented on src/styles/types.ts
> +interface ThemeStructure {
@MMLORENA Intento de PR: toma 4

2023-02-28 11:48 UTC, MMLORENA approved these changes
Pero revisa el tipado del styled components

2023-02-28 11:48 UTC, MMLORENA commented on src/styles/styled.d.ts
> +declare module "styled-components" {
No se hace así el tipado de styled-components

2023-02-28 11:49 UTC, MMLORENA commented
@Sergi-CM contestame las conversaciones de gitHub

2023-02-28 11:51 UTC, Sergi-CM commented on src/components/Button/ButtonStyled.ts
>    font-family: "saira stencil one", sans-serif;
Hecho

2023-02-28 11:54 UTC, Sergi-CM commented on src/styles/styled.d.ts
> +declare module "styled-components" {
Lo investigo

2023-02-28 11:59 UTC, merged